{
  "status": "active", 
  "unique_views": 194, 
  "request_instructor_me": false, 
  "change_log": [
    {
      "type": "create", 
      "anon": "no", 
      "when": "2017-09-27T04:44:58Z", 
      "data": "j82jrdcef3823z", 
      "uid": "i4mub6lmaxh"
    }, 
    {
      "type": "update", 
      "anon": "no", 
      "when": "2017-09-27T04:48:27Z", 
      "data": "j82jvuan7y451t", 
      "uid": "i4mub6lmaxh"
    }, 
    {
      "uid": "hz0pec4uduL", 
      "type": "s_answer", 
      "when": "2017-09-27T04:58:21Z", 
      "to": "j82jrdcbmg123y", 
      "anon": "no", 
      "data": "j82k8l8nq576bl"
    }, 
    {
      "type": "s_answer_update", 
      "anon": "no", 
      "when": "2017-09-27T05:01:10Z", 
      "data": "j82kc7mzf4awl", 
      "uid": "hz0pec4uduL"
    }, 
    {
      "to": "j82jrdcbmg123y", 
      "anon": "no", 
      "when": "2017-09-27T05:20:54Z", 
      "type": "followup", 
      "uid": "i4mub6lmaxh"
    }, 
    {
      "to": "j82jrdcbmg123y", 
      "anon": "no", 
      "when": "2017-09-27T05:45:11Z", 
      "type": "feedback", 
      "uid": "hz0pec4uduL"
    }, 
    {
      "to": "j82jrdcbmg123y", 
      "anon": "no", 
      "when": "2017-09-27T07:53:54Z", 
      "type": "feedback", 
      "uid": "i4mub6lmaxh"
    }, 
    {
      "uid": "gns9oa0pgsO", 
      "type": "i_answer", 
      "when": "2017-09-27T08:30:57Z", 
      "to": "j82jrdcbmg123y", 
      "anon": "no", 
      "data": "j82rtzp15yswt"
    }, 
    {
      "to": "j82jrdcbmg123y", 
      "anon": "no", 
      "when": "2017-09-27T08:55:17Z", 
      "type": "followup", 
      "uid": "i4mub6lmaxh"
    }
  ], 
  "upvote_ids": [], 
  "id": "j82jrdcbmg123y", 
  "bookmarked": 4, 
  "no_answer": 0, 
  "i_edits": [], 
  "is_bookmarked": false, 
  "children": [
    {
      "folders": [], 
      "is_tag_endorse": false, 
      "created": "2017-09-27T04:58:21Z", 
      "type": "s_answer", 
      "tag_endorse_arr": [], 
      "id": "j82k8l8gl626bj", 
      "bucket_name": "Today", 
      "config": {}, 
      "tag_endorse": [], 
      "bucket_order": 2, 
      "data": {
        "embed_links": []
      }, 
      "children": [], 
      "history": [
        {
          "content": "<p>Anaconda is the easiest way to go. Check out <a href=\"https://anaconda.org/anaconda/python\">https://anaconda.org/anaconda/python</a></p>\n<p></p>\n<p>Edit: This is a better link: <a href=\"https://conda.io/docs/user-guide/install/index.html\">https://conda.io/docs/user-guide/install/index.html</a>. I use the full version, as opposed to the mini version.</p>", 
          "anon": "no", 
          "created": "2017-09-27T05:01:10Z", 
          "uid": "hz0pec4uduL", 
          "subject": ""
        }, 
        {
          "content": "<p>Anaconda is the easiest way to go. Check out https://anaconda.org/anaconda/python</p>", 
          "anon": "no", 
          "created": "2017-09-27T04:58:21Z", 
          "uid": "hz0pec4uduL", 
          "subject": ""
        }
      ]
    }, 
    {
      "folders": [], 
      "updated": "2017-09-27T05:20:54Z", 
      "no_upvotes": 0, 
      "uid": "i4mub6lmaxh", 
      "created": "2017-09-27T05:20:54Z", 
      "type": "followup", 
      "no_answer": 0, 
      "id": "j82l1kwu19i57d", 
      "anon": "no", 
      "bucket_name": "Today", 
      "config": {}, 
      "bucket_order": 2, 
      "data": {
        "embed_links": null
      }, 
      "children": [
        {
          "folders": [], 
          "updated": "2017-09-27T05:45:11Z", 
          "uid": "hz0pec4uduL", 
          "created": "2017-09-27T05:45:11Z", 
          "type": "feedback", 
          "id": "j82lwtblfgo4ht", 
          "anon": "no", 
          "bucket_name": "Today", 
          "config": {}, 
          "bucket_order": 2, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>Sorry, I thought you were asking about python distributions. I was running Ubuntu 16.04 and using python without any issues. However, I&#39;ve always run Anaconda python on my systems. Ubuntu comes with python installed by default, but you have to install the libraries, like numpy on top of it. It is usually easier to use a python distribution, like Anaconda. Anaconda comes with numpy already installed and it has the conda package manager to install other packages. I&#39;ve run Anaconda on Windows, Mac, Fedora, Ubuntu and Amazon linux and it has always worked well for me.</p>"
        }, 
        {
          "folders": [], 
          "updated": "2017-09-27T07:53:54Z", 
          "uid": "i4mub6lmaxh", 
          "created": "2017-09-27T07:53:54Z", 
          "type": "feedback", 
          "id": "j82qica3ofa27v", 
          "anon": "no", 
          "bucket_name": "Today", 
          "config": {}, 
          "bucket_order": 2, 
          "data": {
            "embed_links": null
          }, 
          "children": [], 
          "subject": "<p>Thanks again. I&#39;ll try it on Ubuntu.</p>"
        }
      ], 
      "subject": "<p>Thanks for the response.</p>\n<p>How would (ana)conda solve the issue?<br />Surely it doesn&#39;t have a replacement for all system libraries? Which seems to be the problem in my case.<br />I think I&#39;d rather go the VM route. I have Ubuntu Xential up and running so I&#39;m going with that unless the TA&#39;s advise differently.</p>"
    }, 
    {
      "folders": [], 
      "is_tag_endorse": false, 
      "created": "2017-09-27T08:30:57Z", 
      "type": "i_answer", 
      "tag_endorse_arr": [], 
      "id": "j82rtzp03gwws", 
      "bucket_name": "Today", 
      "config": {}, 
      "tag_endorse": [], 
      "bucket_order": 2, 
      "data": {
        "embed_links": []
      }, 
      "children": [], 
      "history": [
        {
          "content": "<p>your numpy installation looks corrupted.\u00a0 did you try to fix it?</p>", 
          "anon": "no", 
          "created": "2017-09-27T08:30:57Z", 
          "uid": "gns9oa0pgsO", 
          "subject": ""
        }
      ]
    }, 
    {
      "folders": [], 
      "updated": "2017-09-27T08:55:17Z", 
      "no_upvotes": 0, 
      "uid": "i4mub6lmaxh", 
      "created": "2017-09-27T08:55:17Z", 
      "type": "followup", 
      "no_answer": 0, 
      "id": "j82sp9uw1sz3i7", 
      "anon": "no", 
      "bucket_name": "Today", 
      "config": {}, 
      "bucket_order": 2, 
      "data": {
        "embed_links": null
      }, 
      "children": [], 
      "subject": "<p>John,</p>\n<p></p>\n<p>I did try fix it. I reinstalled numpy which didn&#39;t help.</p>\n<p>The more I try and fix it the more it seems like a rabbit hole that I won&#39;t escape from.</p>\n<p>So I&#39;ll use Ubuntu via vagrant for now. Thanks.</p>"
    }
  ], 
  "nr": 454, 
  "bucket_order": 2, 
  "type": "question", 
  "folders": [
    "project"
  ], 
  "no_answer_followup": 0, 
  "num_favorites": 1, 
  "bucket_name": "Today", 
  "q_edits": [], 
  "data": {
    "embed_links": []
  }, 
  "request_instructor": 0, 
  "tags": [
    "project", 
    "student"
  ], 
  "created": "2017-09-27T04:44:58Z", 
  "is_tag_good": false, 
  "config": {}, 
  "s_edits": [], 
  "my_favorite": false, 
  "default_anonymity": "no", 
  "t": 1509145213964, 
  "tag_good": [], 
  "tag_good_arr": [], 
  "history": [
    {
      "content": "<p>Hi.<br /><br />I know this project is in python and we should be able to run in any distro with python2 and numpy installed but I seem to be having problems on arch linux:<br /><br /></p>\n<pre>python2 bloom.py -c testConfigHashType2.txt -i testInput.txt -o testOutput.txt -v validResHashType2.txt\nTraceback (most recent call last):\n  File &#34;bloom.py&#34;, line 7, in &lt;module&gt;\n    import numpy.random as random\n  File &#34;/usr/lib/python2.7/site-packages/numpy/__init__.py&#34;, line 142, in &lt;module&gt;\n    from . import add_newdocs\n  File &#34;/usr/lib/python2.7/site-packages/numpy/add_newdocs.py&#34;, line 13, in &lt;module&gt;\n    from numpy.lib import add_newdoc\n  File &#34;/usr/lib/python2.7/site-packages/numpy/lib/__init__.py&#34;, line 8, in &lt;module&gt;\n    from .type_check import *\n  File &#34;/usr/lib/python2.7/site-packages/numpy/lib/type_check.py&#34;, line 11, in &lt;module&gt;\n    import numpy.core.numeric as _nx\n  File &#34;/usr/lib/python2.7/site-packages/numpy/core/__init__.py&#34;, line 26, in &lt;module&gt;\n    raise ImportError(msg)\nImportError: \nImporting the multiarray numpy extension module failed.  Most\nlikely you are trying to import a failed build of numpy.\nIf you&#39;re working with a numpy git repo, try &#96;git clean -xdf&#96; (removes all\nfiles not under version control).  Otherwise reinstall numpy.\n\nOriginal error was: libcblas.so.3: cannot open shared object file: No such file or directory\n</pre>\n<p>This looks like an ugly error that may take some time to figure out so I&#39;ll rather just run it in a VM.<br />Any suggestions on what distro to use, would the latest LTS Ubuntu (Xenial) be fine?</p>\n<p>Any chance we can know what system will be used to test our project?<br /><br /><br /></p>", 
      "anon": "no", 
      "created": "2017-09-27T04:48:27Z", 
      "uid": "i4mub6lmaxh", 
      "subject": "Suggested distro for project?"
    }, 
    {
      "content": "<p>Hi.<br /><br />I know this project is in python and we should be able to run in any distro with python2 and numpy installed but I seem to be having problems on arch linux:<br /><br /></p>\n<pre>python2 bloom.py -c testConfigHashType2.txt -i testInput.txt -o testOutput.txt -v validResHashType2.txt\nTraceback (most recent call last):\n  File &#34;bloom.py&#34;, line 7, in &lt;module&gt;\n    import numpy.random as random\n  File &#34;/usr/lib/python2.7/site-packages/numpy/__init__.py&#34;, line 142, in &lt;module&gt;\n    from . import add_newdocs\n  File &#34;/usr/lib/python2.7/site-packages/numpy/add_newdocs.py&#34;, line 13, in &lt;module&gt;\n    from numpy.lib import add_newdoc\n  File &#34;/usr/lib/python2.7/site-packages/numpy/lib/__init__.py&#34;, line 8, in &lt;module&gt;\n    from .type_check import *\n  File &#34;/usr/lib/python2.7/site-packages/numpy/lib/type_check.py&#34;, line 11, in &lt;module&gt;\n    import numpy.core.numeric as _nx\n  File &#34;/usr/lib/python2.7/site-packages/numpy/core/__init__.py&#34;, line 26, in &lt;module&gt;\n    raise ImportError(msg)\nImportError: \nImporting the multiarray numpy extension module failed.  Most\nlikely you are trying to import a failed build of numpy.\nIf you&#39;re working with a numpy git repo, try &#96;git clean -xdf&#96; (removes all\nfiles not under version control).  Otherwise reinstall numpy.\n\nOriginal error was: libcblas.so.3: cannot open shared object file: No such file or directory\n</pre>\n<p>This looks like an ugly error that may take some time to figure out so I&#39;ll rather just run it in a VM.<br />Any suggestions on what distro to use, would the latest LTS Ubuntu be fine? Any chance we can know what system will be used to test our project?<br /><br /><br /></p>", 
      "anon": "no", 
      "created": "2017-09-27T04:44:58Z", 
      "uid": "i4mub6lmaxh", 
      "subject": "Suggested distro for project?"
    }
  ]
}